'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmPlProfesiograma
    
    '''<summary>
    '''pnlCtrProfesiograma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCtrProfesiograma As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblPathPagina control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPathPagina As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ctrProfesiograma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrProfesiograma As Global.wSoftSGSST.ctrProfesiograma
End Class
