'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmMtRgMatrizRiesgos
    
    '''<summary>
    '''upnlMatrizRiesgos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnlMatrizRiesgos As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitulo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ibtnFiltrosConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnFiltrosConsulta As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ibtnEscogerCampos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnEscogerCampos As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ibtnMatrizPDF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnMatrizPDF As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''pnlMatrizRiesgos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMatrizRiesgos As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''gvMatrizRiesgos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvMatrizRiesgos As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''ddlNumPagMatrizRiesgos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNumPagMatrizRiesgos As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''odsMatrizRiesgos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsMatrizRiesgos As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
