'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmMtRgMatrizRiesgos
    
    '''<summary>
    '''upnlMatrizRiesgos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnlMatrizRiesgos As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblPathPagina control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPathPagina As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitulo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ibtnFiltrosConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnFiltrosConsulta As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ibtnEscogerCampos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnEscogerCampos As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ibtnMatrizPDF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnMatrizPDF As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''pnlMatrizRiesgos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMatrizRiesgos As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''gvMatrizRiesgos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvMatrizRiesgos As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''ddlNumPagMatrizRiesgos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNumPagMatrizRiesgos As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''odsMatrizRiesgos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsMatrizRiesgos As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''btnFake123 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFake123 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''modalInfoMedIntervencion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modalInfoMedIntervencion As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''pnlInfoMedIntervencion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlInfoMedIntervencion As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''upnlInfoMedIntervencion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnlInfoMedIntervencion As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''ibtnCerrarMedIntervencion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnCerrarMedIntervencion As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblTituloInfoAdicPeligro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloInfoAdicPeligro As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlInfoBasicaPeligro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlInfoBasicaPeligro As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''bNomDescPeligro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bNomDescPeligro As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDescPeligro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescPeligro As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNomClasiPeligro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNomClasiPeligro As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblClasiPeligro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClasiPeligro As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlInfoAdicParamPeligro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlInfoAdicParamPeligro As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblNomEvalPeligro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNomEvalPeligro As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblEvalPeligro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEvalPeligro As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNomNumExpuestos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNomNumExpuestos As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNumExpuestos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumExpuestos As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNomPeorConsec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNomPeorConsec As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPeorConsec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPeorConsec As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNomReqLegal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNomReqLegal As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblReqLegal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReqLegal As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlMedIntervencion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMedIntervencion As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ctrMtRsMedIntervencion1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrMtRsMedIntervencion1 As Global.wSoftSGSST.ctrMtRsMedIntervencion
End Class
