'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmPlPerfDemografico
    
    '''<summary>
    '''upnlPerfDemografico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnlPerfDemografico As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblPathPagina control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPathPagina As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitulo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ibtnLimpiar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnLimpiar As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ibtnNuevaConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnNuevaConsulta As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ibtnNuevoEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnNuevoEmpleado As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lbtnLimpiarForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnLimpiarForm As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''pnlBusEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBusEmpleado As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpleado As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ctrDinaConsObj1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrDinaConsObj1 As Global.wSoftSGSST.ctrDinaConsObj
    
    '''<summary>
    '''pnlInfoEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlInfoEmpleado As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ctrInfoEmpleado1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrInfoEmpleado1 As Global.wSoftSGSST.ctrInfoEmpleado
End Class
