'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmMenuPlanear
    
    '''<summary>
    '''imTotalPlanear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imTotalPlanear As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''imTotalProfesiograma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imTotalProfesiograma As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''imTotalPerfilSocioDemografico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imTotalPerfilSocioDemografico As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''imTotalMatrizRiesgos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imTotalMatrizRiesgos As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''imTotalMatrizLegal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imTotalMatrizLegal As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''imTotalProgramasVigilancia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imTotalProgramasVigilancia As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''imTotalProgramasGestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imTotalProgramasGestion As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''imTotalPoliticasYObjetivos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imTotalPoliticasYObjetivos As Global.System.Web.UI.WebControls.Image
End Class
