'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctrActividadesYPeligros
    
    '''<summary>
    '''pnlActividad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlActividad As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ibtCerrar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtCerrar As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblRiesgos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRiesgos As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNomNomCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNomNomCargo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNomCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNomCargo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblInfor1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfor1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblActividad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblActividad As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ctrDinaConsObjActividad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrDinaConsObjActividad As Global.wSoftSGSST.ctrDinaConsObj
    
    '''<summary>
    '''ibtnNuevaActivdad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnNuevaActivdad As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblInfor2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfor2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlNuevaActividad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNuevaActividad As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtNuevaActividad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNuevaActividad As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ibtnGuardarNuevaAct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnGuardarNuevaAct As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ibtnCerrarNuevaAct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnCerrarNuevaAct As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblInfor3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfor3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblRiesXAct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRiesXAct As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''upnlPeligro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnlPeligro As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''pnlGvPeligro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGvPeligro As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''gvPeligro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvPeligro As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''ibntNuevoRiesgo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibntNuevoRiesgo As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ibtnCargar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnCargar As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''pnlGvActRiesgos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGvActRiesgos As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlPeligrosXCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPeligrosXCargo As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''gvPeligrosXCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvPeligrosXCargo As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''btnfake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnfake As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ModalPopupExtenderNuevoRiesgo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalPopupExtenderNuevoRiesgo As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''pnlDescClasRies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDescClasRies As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''upnlDescClasRies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnlDescClasRies As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''btnCerrarModalRiesgo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCerrarModalRiesgo As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblNuevoRiesgo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNuevoRiesgo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDescripcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescripcion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDescripcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescripcion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblCladificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCladificacion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlClasificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlClasificacion As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblRiesgo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRiesgo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlRiesgo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRiesgo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ibtAgregarDescClasRies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtAgregarDescClasRies As Global.System.Web.UI.WebControls.ImageButton
End Class
