'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctrActividadesYRiesgos
    
    '''<summary>
    '''pnlGvActRiesgos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGvActRiesgos As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ibtCerrar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtCerrar As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblRiesgos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRiesgos As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNomNomCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNomNomCargo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNomCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNomCargo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ibtnAgregarActividad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnAgregarActividad As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''pnlGvActividad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGvActividad As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''gvActividades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvActividades As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''pnlActividad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlActividad As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ibtnCerrarActividad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnCerrarActividad As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblRegNuevaAct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRegNuevaAct As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ctrDinaConsObj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrDinaConsObj As Global.wSoftSGSST.ctrDinaConsObj
    
    '''<summary>
    '''ibnIncluirActividad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibnIncluirActividad As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ibntNuevaActividad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibntNuevaActividad As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''pnlNuevaActividad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNuevaActividad As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblNuevaAct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNuevaAct As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtNuevaActividad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNuevaActividad As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ibtnGuardarNuevaAct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnGuardarNuevaAct As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ibtnCerrarNuevaAct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnCerrarNuevaAct As Global.System.Web.UI.WebControls.ImageButton
End Class
