'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctrCargosEmpleado
    
    '''<summary>
    '''upnlCargosEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnlCargosEmpleado As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCargo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCargo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ibtnRequisitos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnRequisitos As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ibtnHistorico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnHistorico As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ibtnRelNuevoCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnRelNuevoCargo As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''btnFake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFake As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''modalHistCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modalHistCargo As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''pnlHistCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlHistCargo As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''upnlHistCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnlHistCargo As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''ibtnCerrarHistCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnCerrarHistCargo As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblHistCargos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHistCargos As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlGvHistCargos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGvHistCargos As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''gvHistCargos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvHistCargos As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''odsHistCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsHistCargo As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''btnFake2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFake2 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''modalReqCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modalReqCargo As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''pnlReqCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlReqCargo As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''upnlReqCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnlReqCargo As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''ibtnCerrarReqCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnCerrarReqCargo As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblReqCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReqCargo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCargoActual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCargoActual As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblInfoCargoActual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfoCargoActual As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblEducacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEducacion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblInfoEducacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfoEducacion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblProfesion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProfesion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblInfoProfesion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfoProfesion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblExperienciaAnios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExperienciaAnios As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblInfoExperienciaAnios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfoExperienciaAnios As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblHabilidades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHabilidades As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblInfoHabilidades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfoHabilidades As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnFake3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFake3 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''modalRelNuevoCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modalRelNuevoCargo As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''pnlRelNuevoCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRelNuevoCargo As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''upnlRelNuevoCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnlRelNuevoCargo As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''ibtnCerrarRelNuevoCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnCerrarRelNuevoCargo As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblRelNuevoCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRelNuevoCargo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblInfoCargoActualRelNuevoCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfoCargoActualRelNuevoCargo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAstValNuevoCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAstValNuevoCargo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNuevoCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNuevoCargo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlNuevoCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNuevoCargo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblAstValFchIngresoCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAstValFchIngresoCargo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFchIngresoCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFchIngresoCargo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ctrFechaIngreso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrFechaIngreso As Global.wSoftSGSST.ctrFecha
    
    '''<summary>
    '''ibtnGuardarCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnGuardarCargo As Global.System.Web.UI.WebControls.ImageButton
End Class
