'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctrEvaluacionPeligro
    
    '''<summary>
    '''pnlEvaluacionPeligro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEvaluacionPeligro As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlDescripcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDescripcion As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblNomDescPeligro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNomDescPeligro As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDescPeligro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescPeligro As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNomClasifPeligro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNomClasifPeligro As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblClasifPeligro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClasifPeligro As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblExplicacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExplicacion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblExplicacion2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExplicacion2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNomCriterio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNomCriterio As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNomValoracion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNomValoracion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNomExpValoracion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNomExpValoracion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNivDef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNivDef As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlNivDef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNivDef As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''pnlExpNivDef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlExpNivDef As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblExpNivDef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExpNivDef As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNivExp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNivExp As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlNivExp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNivExp As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''pnlExpNivExp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlExpNivExp As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblExpNivExp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExpNivExp As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNivProb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNivProb As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblValNivProb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblValNivProb As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlExpNivProb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlExpNivProb As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblExpNivProb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExpNivProb As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNivCons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNivCons As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlNivCons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNivCons As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''pnlExpNivCons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlExpNivCons As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblExpNivCons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExpNivCons As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNivRies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNivRies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblValNivRies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblValNivRies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlExpNivRies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlExpNivRies As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblExpNivRies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExpNivRies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAcepNiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAcepNiv As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblValAcepNiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblValAcepNiv As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlExpValAcep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlExpValAcep As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblExpValAcep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExpValAcep As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ibtnGuardarEval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnGuardarEval As Global.System.Web.UI.WebControls.ImageButton
End Class
