'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctrInfoEmpleado
    
    '''<summary>
    '''upnlInfoEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnlInfoEmpleado As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''pnlInfoBasicaEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlInfoBasicaEmpleado As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''imEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imEmpleado As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblNombreEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNombreEmpleado As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAnios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAnios As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTipDocNumDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTipDocNumDoc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCargo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ibtnEditarInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnEditarInfo As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''pnlInfoUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlInfoUsuario As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlInfoUsuarioCreaMod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlInfoUsuarioCreaMod As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblNombres control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNombres As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtNombres control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNombres As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblApellidos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblApellidos As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtApellidos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtApellidos As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblTipDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTipDoc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlTipDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipDoc As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblNumDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumDoc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtNumDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumDoc As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblGenero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGenero As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlGenero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlGenero As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblFchNacimiento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFchNacimiento As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ctrFechaNacimiento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrFechaNacimiento As Global.wSoftSGSST.ctrFecha
    
    '''<summary>
    '''pnlDeptoCiudad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDeptoCiudad As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ctrPaisCiudadDep1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrPaisCiudadDep1 As Global.wSoftSGSST.ctrPaisCiudadDep
    
    '''<summary>
    '''lblEducacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEducacion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlEducacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEducacion As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblProfesion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProfesion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlProfesion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProfesion As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblEstCivil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEstCivil As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlEstCivil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEstCivil As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ctrCargosEmpleado1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrCargosEmpleado1 As Global.wSoftSGSST.ctrCargosEmpleado
    
    '''<summary>
    '''lblTipoCont control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTipoCont As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlTipoContrato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoContrato As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblFchIngreso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFchIngreso As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ctrFechaIngreso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrFechaIngreso As Global.wSoftSGSST.ctrFecha
    
    '''<summary>
    '''lblImagen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImagen As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''fuImagenEmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuImagenEmp As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''ibtnGuardarInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnGuardarInfo As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ibtnInfoLaboral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnInfoLaboral As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ibtnAccidentesEnf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnAccidentesEnf As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ibtnConceptosMed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnConceptosMed As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ibtnRiesgosCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnRiesgosCargo As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ibtnResponSGSST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnResponSGSST As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''btnFake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFake As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''modalInfoRiesgosCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modalInfoRiesgosCargo As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''pnlInfoRiesgosCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlInfoRiesgosCargo As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''upnlInfoRiesgosCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnlInfoRiesgosCargo As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''ibtnCerrrarModalInfoRiesgoCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnCerrrarModalInfoRiesgoCargo As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblTituloRiesgosCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloRiesgosCargo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNomCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNomCargo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCargoInfoRiesgo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCargoInfoRiesgo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlRiesgosCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRiesgosCargo As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''gvRiesgosCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvRiesgosCargo As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''odsRiesgosCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsRiesgosCargo As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
