'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctrInfoPeligro
    
    '''<summary>
    '''lblNomActividad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNomActividad As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblActividad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblActividad As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ctrProceso1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrProceso1 As Global.wSoftSGSST.ctrProceso
    
    '''<summary>
    '''pnlCargos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCargos As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''gvCargos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvCargos As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''odsCargos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsCargos As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''ctrLugar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrLugar1 As Global.wSoftSGSST.ctrLugar
    
    '''<summary>
    '''lblRutinaria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRutinaria As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlRutinaria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRutinaria As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblDescripcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescripcion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDescripcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescripcion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblNomClasificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNomClasificacion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblClasificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClasificacion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNomRiesgo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNomRiesgo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblRiesgo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRiesgo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ibtnIncluirRiesgo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnIncluirRiesgo As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ibtnCtrExistentes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnCtrExistentes As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ibtnEvaluacionRiesgo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnEvaluacionRiesgo As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ibtnCriControles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnCriControles As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ibtnMedIntervencion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnMedIntervencion As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''btnFake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFake As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''modalInfoAdicPeligro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modalInfoAdicPeligro As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''pnlInfoAdicPeligro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlInfoAdicPeligro As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''upnlInfoAdicPeligro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnlInfoAdicPeligro As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''ibtnCerrarInfoAdicPeligro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnCerrarInfoAdicPeligro As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblTituloInfoAdicPeligro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloInfoAdicPeligro As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlInfoBasicaPeligro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlInfoBasicaPeligro As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''bNomDescPeligro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bNomDescPeligro As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDescPeligro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescPeligro As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNomClasiPeligro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNomClasiPeligro As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblClasiPeligro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClasiPeligro As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlCtrExistentes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCtrExistentes As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ctrMtRsControlesExistentes1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrMtRsControlesExistentes1 As Global.wSoftSGSST.ctrMtRsControlesExistentes
    
    '''<summary>
    '''pnlCriteriosCtr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCriteriosCtr As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ctrMtRsCriControles1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrMtRsCriControles1 As Global.wSoftSGSST.ctrMtRsCriControles
    
    '''<summary>
    '''pnlMedIntervencion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMedIntervencion As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ctrMtRsMedIntervencion1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrMtRsMedIntervencion1 As Global.wSoftSGSST.ctrMtRsMedIntervencion
    
    '''<summary>
    '''btnFake2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFake2 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''modalEvalPeligro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modalEvalPeligro As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''pnlEvalPeligro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEvalPeligro As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ctrEvaluacionPeligro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrEvaluacionPeligro As Global.wSoftSGSST.ctrEvaluacionPeligro
End Class
