'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctrLugar
    
    '''<summary>
    '''lblLugar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLugar As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlLugar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlLugar As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtLugar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLugar As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ibtnIncluir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnIncluir As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ibtnGuardar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnGuardar As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ibtnCerrar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnCerrar As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ibtnAgregar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnAgregar As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''pnlGvLugar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGvLugar As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''gvLugar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvLugar As Global.System.Web.UI.WebControls.GridView
End Class
