'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctrMtRsCriControles
    
    '''<summary>
    '''lblNumExpuestos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumExpuestos As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtNumExpuestos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumExpuestos As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''blPeorConsec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents blPeorConsec As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtPeorConsec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPeorConsec As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblEstReqLega control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEstReqLega As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlEstReqLegal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEstReqLegal As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ibtnGuardarInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnGuardarInfo As Global.System.Web.UI.WebControls.ImageButton
End Class
