'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctrMtRsControlesExistentes
    
    '''<summary>
    '''lblCtrFte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCtrFte As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCtrFuente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCtrFuente As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblCtrMedio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCtrMedio As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCtrMedio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCtrMedio As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblCtrIndividuo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCtrIndividuo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCtrIndividuo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCtrIndividuo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ibtnGuardarInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnGuardarInfo As Global.System.Web.UI.WebControls.ImageButton
End Class
