'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctrMtRsMedIntervencion
    
    '''<summary>
    '''lblEliminacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEliminacion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtEliminacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEliminacion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblSustitucion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSustitucion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSustitucion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSustitucion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblCtrIngenieria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCtrIngenieria As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCtrIngenieria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCtrIngenieria As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblCtrAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCtrAdmin As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCtrAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCtrAdmin As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblEEPP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEEPP As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtEEPP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEEPP As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ibtnGuardarInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnGuardarInfo As Global.System.Web.UI.WebControls.ImageButton
End Class
