'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctrProfesiograma
    
    '''<summary>
    '''lblProfesiograma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProfesiograma As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ibtnNuevaConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnNuevaConsulta As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ibtnNuevoProfesiograma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnNuevoProfesiograma As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblNomCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNomCargo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtNomCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNomCargo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblNomCargoObliga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNomCargoObliga As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCodCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodCargo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCodCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodCargo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblCodCargoObliga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodCargoObliga As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblObjCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblObjCargo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtObjCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObjCargo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblActividades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblActividades As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtActividades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtActividades As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblActividadesObliga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblActividadesObliga As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblEducacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEducacion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlEducacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEducacion As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblProfesion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProfesion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlProfesion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProfesion As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblExperiencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExperiencia As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtExperiencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExperiencia As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblExperienciaAnos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExperienciaAnos As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtExperienciaAnos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExperienciaAnos As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblHabilidades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHabilidades As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtHabilidades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHabilidades As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblAQuienReporta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAQuienReporta As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlAQuienReporta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAQuienReporta As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblQuienLePreporta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQuienLePreporta As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ctrDinaConsObj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrDinaConsObj As Global.wSoftSGSST.ctrDinaConsObj
    
    '''<summary>
    '''pnlGvQuienLeReporta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGvQuienLeReporta As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''gvQuienLeReporta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvQuienLeReporta As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''ibtnAgregarQuienLeReporta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnAgregarQuienLeReporta As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblAreaDelCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAreaDelCargo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlAreaDelCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAreaDelCargo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ibtnRiesgos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnRiesgos As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''itbnRqFisicos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents itbnRqFisicos As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ibtnCondicSalud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnCondicSalud As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ibtEpp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtEpp As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ibtnResponsabilidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnResponsabilidad As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ibtnGuardar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnGuardar As Global.System.Web.UI.WebControls.ImageButton
End Class
